#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	[ -x /usr/libexec/hwdash-wanmon ] || return 0
	procd_open_instance
	procd_set_param command /usr/libexec/hwdash-wanmon
	procd_set_param respawn
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}
